#Graph section keys
TOOLBAR_KEY = 'TOOLBAR'
FIGURE_KEY = 'FIGURE'

#Curve option keys
RANDOM_GEN_KEY = 'RANDOM_OPTIONS'
PLOT_ASYMP_KEY = 'PLOT_ASYMPTOTES'
PLOT_CURV_ASYMP_KEY = 'EXCLUDE_CURV_ASYMPTOTES'
NUM_DEG_SPIN_KEY = 'NUM_DEG_SPIN'
DEN_DEG_SPIN_KEY = 'DEN_DEG_SPIN'
FORCE_NUM_DEG_KEY = 'FORCE_NUM_DEG'
FORCE_DEN_DEG_KEY = 'FORCE_DEN_DEG'
SHOW_NEXT_GEN_KEY = 'SHOW_NEXT_GEN'
CURVE_LABEL_KEY = 'CURVE_LABEL'

#Analytics section keys
ANALYTIC_SEC_KEY = 'ANALYTIC_SECTION'
ROOTS_KEY = 'ROOTS'
Y_INTERCEPT_KEY = 'Y_INTERCEPT'
STAT_POINTS_KEY = 'STATIONARY_POINTS'
INFLEC_POINTS_KEY = 'INFLECTION_POINTS'

#Button keys
GEN_KEY = 'GENERATE'
SHOW_KEY = 'SHOW'
HIDE_KEY = 'HIDE'
UPDATE_KEY = 'UDPATE'
EXIT_KEY = 'EXIT'

#Misc keys
PROG_KEY = 'PROGRESS_MESSAGE'